version: "3.9"

services:

  api:
    image: natley30/toxicity-api
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: toxicity-api
    ports:
      - "5000:5000"
    environment:
      DAGSHUB_API_KEY: ${DAGSHUB_API_KEY}
      DAGSHUB_USERNAME: ${DAGSHUB_USERNAME}
    networks:
      - toxicity_net

  webapp:
    image: natley30/toxicity-web
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: toxicity-app
    ports:
      - "8501:8501"
    environment:
      API_URL: "http://api:5000/predict"
      DAGSHUB_API_KEY: ${DAGSHUB_API_KEY}
      DAGSHUB_USERNAME: ${DAGSHUB_USERNAME}
    depends_on:
      - api
    networks:
      - toxicity_net


networks:
  toxicity_net:
    driver: bridge
